In [1]:
from tensorflow.keras.models import load_model
import cv2
from tensorflow.keras.preprocessing import image

In [2]:
model = load_model('facerecogvgg.h5')

In [3]:
from PIL import Image

In [4]:
face_clf = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')



labels_dict = {0:'Man',1:'Woman'}

colors_dict = {0:(0,255,0),1:(0,0,255)}

In [5]:
import numpy as np

In [6]:
source = cv2.VideoCapture(0)
while(1):
        ret,img = source.read()
        faces = face_clf.detectMultiScale(img,1.3,5)
        for (x,y,w,h) in faces:
            cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
            face = img[y:y+h,x:x+h]
        #return crop_face
        #face = resizeface(img)
            if type(face) is np.ndarray:
                resize = cv2.resize(face,(224,224))
                im = Image.fromarray(resize,'RGB')
                img_array = np.array(im)
                img_array = np.expand_dims(img_array,axis = 0)
                pred = model.predict(img_array)

                print(pred)

                if(pred[0][0] == 1):
                    name = 'Male'
                    cv2.putText(img,name,(50,50),cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

                elif(pred[0][1] == 1):
                    name = 'Female'
                    cv2.putText(img,name,(50,50),cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

            else:
                cv2.putText(ret,"No face Found",(50,50),cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        
        cv2.imshow('Video',img)

        if cv2.waitKey(1) & 0xFF == ord('q'):
                break
source.release()
cv2.destroyAllWindows()


[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
